.

diff --git a/pipelines/templates/cache-dependencies-template.yml b/pipelines/templates/cache-dependencies-template.yml
--- a/pipelines/templates/cache-dependencies-template.yml
+++ b/pipelines/templates/cache-dependencies-template.yml
@@ -27,72 +27,61 @@ steps:
   displayName: (legacy) Activate legacy dependencies
   condition: and(succeeded(), contains('${{ parameters.platform }}', 'legacy'))
 
-#- script: |
-#    set -e
-#    echo '===== develop ====='
-#    ./pip-install -r dependencies/develop.txt
-#    #echo '===== required ====='
-#    #./pip-install -r dependencies/required.txt
-#    #echo '===== required extra ====='
-#    #./pip-install -r dependencies/required_extra.txt
-#    #echo '===== recommended ====='
-#    #./pip-install -r dependencies/recommended.txt
-#    echo '===== fix shebang ====='
-#    python test/vso_tools/fix_shebang.py python-packages/bin
-#  displayName: (POSIX) Install Python packages
-#  condition: and(succeeded(), not(contains('${{ parameters.platform }}', 'windows')))
-#
-## FIXME: It does not stop on failure. Tried "ErrorActionPreference" with no luck.
-#- powershell: |
-#    echo '===== develop ====='
-#    ./pip-install -r dependencies/develop.txt
-#    #echo '===== required ====='
-#    #./pip-install -r dependencies/required.txt
-#    #echo '===== required extra ====='
-#    #./pip-install -r dependencies/required_extra.txt
-#    #echo '===== recommended ====='
-#    #./pip-install -r dependencies/recommended.txt
-#  displayName: (Windows) Install Python packages
-#  condition: and(succeeded(), contains('${{ parameters.platform }}', 'windows'))
-#
-### FIXME:
-### numpy version may change several times during installation, and it has an ABI change in recent versions.
-### We must make sure ConfigSpaceNNI is built against correct numpy version, or it will fail on import.
-##- script: |
-##    python -m pip uninstall -y ConfigSpaceNNI
-##    ./pip-install --no-cache-dir ConfigSpaceNNI
-##  displayName: (Ubuntu) Rebuild ConfigSpaceNNI
-##  condition: and(succeeded(), contains('${{ parameters.platform }}', 'ubuntu'))
-#
-#- script: |
-#    yarn --cwd ts/nni_manager install
-#  displayName: Install NNI Manager dependencies
-#
-#- script: |
-#    yarn --cwd ts/webui install
-#  displayName: Install Web UI dependencies
-#
-#- script: |
-#    python test/vso_tools/pack_dependencies.py dependencies.zip
-#  displayName: Create cache archive
+- script: |
+    set -e
+    echo '===== develop ====='
+    ./pip-install -r dependencies/develop.txt
+    echo '===== required ====='
+    ./pip-install -r dependencies/required.txt
+    echo '===== required extra ====='
+    ./pip-install -r dependencies/required_extra.txt
+    echo '===== recommended ====='
+    ./pip-install -r dependencies/recommended.txt
+    echo '===== fix shebang ====='
+    python test/vso_tools/fix_shebang.py python-packages/bin
+  displayName: (POSIX) Install Python packages
+  condition: and(succeeded(), not(contains('${{ parameters.platform }}', 'windows')))
+
+# FIXME: It does not stop on failure. Tried "ErrorActionPreference" with no luck.
+- powershell: |
+    echo '===== develop ====='
+    ./pip-install -r dependencies/develop.txt
+    echo '===== required ====='
+    ./pip-install -r dependencies/required.txt
+    echo '===== required extra ====='
+    ./pip-install -r dependencies/required_extra.txt
+    echo '===== recommended ====='
+    ./pip-install -r dependencies/recommended.txt
+  displayName: (Windows) Install Python packages
+  condition: and(succeeded(), contains('${{ parameters.platform }}', 'windows'))
+
+# FIXME:
+# numpy version may change several times during installation, and it has an ABI change in recent versions.
+# We must make sure ConfigSpaceNNI is built against correct numpy version, or it will fail on import.
+- script: |
+    python -m pip uninstall -y ConfigSpaceNNI
+    ./pip-install --no-cache-dir ConfigSpaceNNI
+  displayName: (Ubuntu) Rebuild ConfigSpaceNNI
+  condition: and(succeeded(), contains('${{ parameters.platform }}', 'ubuntu'))
 
 - script: |
-    azcopy copy setup.py 'https://nni.blob.core.windows.net/cache/dependencies-${{ parameters.platform }}.zip?$(sas_token)'
+    yarn --cwd ts/nni_manager install
+  displayName: Install NNI Manager dependencies
+
+- script: |
+    yarn --cwd ts/webui install
+  displayName: Install Web UI dependencies
+
+- script: |
+    python test/vso_tools/pack_dependencies.py dependencies.zip
+  displayName: Create cache archive
+
+- script: |
+    azcopy copy dependencies.zip 'https://nni.blob.core.windows.net/cache/dependencies-${{ parameters.platform }}.zip?$(sas_token)'
   displayName: (POSIX) Upload cache archive
   condition: and(succeeded(), not(contains('${{ parameters.platform }}', 'windows')))
 
 - powershell: |
-    azcopy copy setup.py 'https://nni.blob.core.windows.net/cache/dependencies-${{ parameters.platform }}.zip?$(sas_token)'
-    echo '=========='
-    ls /Users/VssAdministrator/.azcopy
-    echo '=========='
-    cat /sers/VssAdministrator/.azcopy/*.log
+    azcopy copy dependencies.zip 'https://nni.blob.core.windows.net/cache/dependencies-${{ parameters.platform }}.zip?$(sas_token)'
   displayName: (Windows) Upload cache archive
   condition: and(succeeded(), contains('${{ parameters.platform }}', 'windows'))
-
-- script: |
-    ls /home/vsts/.azcopy/
-    echo '=========='
-    cat /home/vsts/.azcopy/*.log
-  displayName: (Ubuntu) debug
-  condition: contains('${{ parameters.platform }}', 'ubuntu')
