.

diff --git a/pipelines/templates/save-crashed-info.yml b/pipelines/templates/save-crashed-info.yml
--- a/pipelines/templates/save-crashed-info.yml
+++ b/pipelines/templates/save-crashed-info.yml
@@ -19,22 +19,30 @@ steps:
 - script: |
     set -e
     export EXPERIMENT_ID=$(echo ${EXPERIMENT_DIR} | sed -e 's/\/.*\///g')
-    sudo docker cp $(Build.BuildId):/tmp/nni-experiments/${EXPERIMENT_ID} ${EXPERIMENT_DIR}/remote
+    sudo docker cp $(Build.BuildId):/tmp/nni-experiments/${EXPERIMENT_ID} ${EXPERIMENT_DIR}/remote && echo "Copy successful" || echo "Copy failed"
   condition: and(variables['experiment_dir'], ${{ parameters.remote }}, not(contains(variables['Agent.OS'], 'Windows')))
   displayName: (failed) (POSIX) Harvest remote trial logs
 
 - powershell: |
-    $latest_dir = (gci ~/nni-experiments -exclude _latest | ? { $_.PSIsContainer } | sort CreationTime)[-1]
-    echo "Latest experiment directory: $latest_dir"
-    echo "##vso[task.setvariable variable=experiment_dir]$latest_dir"
+    $latestDir = (gci ~/nni-experiments -exclude _latest | ? { $_.PSIsContainer } | sort CreationTime)[-1]
+    echo "Latest experiment directory: $latestDir"
+    echo "##vso[task.setvariable variable=experiment_dir]$latestDir"
   condition: and(failed(), contains(variables['Agent.OS'], 'Windows'))
   displayName: (failed) (Windows) Latest experiment directory
 
 - powershell: |
-    $latest_dir = gci $(experiment_dir)
-    $experiment_id = $latest_dir.name
-    Copy-Item -Path "C:\Users\nniuser\AppData\Local\Temp\nni-experiments\${experiment_id}" `
-      -Destination "${latest_dir}\remote" -Recurse
+    $latestDir = gci $(experiment_dir)
+    $experimentId = $latestDir.name
+    $remotePath = "C:\Users\nniuser\AppData\Local\Temp\nni-experiments\${experimentId}"
+    $destPath = "${latestDir}\remote"
+
+    if (Test-Path $remotePath) {
+      Write-Host "Copying $remotePath to $destPath"
+      Copy-Item $remotePath -Destination $destPath -Recurse
+    }
+    else {
+      Write-host "$remotePath doesn't exist"
+    }
   condition: and(variables['experiment_dir'], ${{ parameters.remote }}, contains(variables['Agent.OS'], 'Windows'))
   displayName: (failed) (Windows) Harvest remote trial logs
 
