updates

diff --git a/deployment/deployment-pipelines.yml b/deployment/deployment-pipelines.yml
--- a/deployment/deployment-pipelines.yml
+++ b/deployment/deployment-pipelines.yml
@@ -15,9 +15,9 @@ jobs:
       if [[ $(build_version) =~ ^v[0-9](.[0-9]){1,3}$ ]]; then
         echo 'valid build version $(build_version)'
         echo `git describe --tags --abbrev=0`
-      #else
-      #  echo 'invalid build version $(build_version)'
-      #  exit 1
+      else
+        echo 'invalid build version $(build_version)'
+        exit 1
       fi
     condition: eq( variables['build_type'], 'prerelease' )
     displayName: 'Validate prerelease version number'
